metadata:
  name: call-center-demo
  created: '2025-08-15T16:09:53.750000'
kind: project
status:
  state: online
spec:
  load_source_on_run: false
  functions:
  - url: hub://structured_data_generator
    name: structured-data-generator
    kind: job
  - url: ./src/calls_generation/conversations_generator.py
    name: conversations-generator
    kind: job
    image: .mlrun-project-image-call-center-demo
  - url: hub://text_to_audio_generator
    name: text-to-audio-generator
    kind: job
  - url: ./src/calls_analysis/db_management.py
    name: db-management
    kind: job
    image: .mlrun-project-image-call-center-demo
  - url: hub://silero_vad
    name: silero-vad
    kind: job
  - url: hub://transcribe
    name: transcription
    kind: job
  - url: hub://pii_recognizer
    name: pii-recognition
    kind: job
  - url: hub://question_answering
    name: question-answering
    kind: job
  - url: ./src/calls_analysis/postprocessing.py
    name: postprocessing
    kind: job
    image: .mlrun-project-image-call-center-demo
  - name: call-center-ui
    kind: application
    requirements:
    - vizro==0.1.38
    - gunicorn
  desired_state: online
  build:
    commands:
    - apt-get update -y && apt-get install ffmpeg -y
    - pip install transformers==4.44.1
    - pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cpu
    - pip install bitsandbytes==0.41.1 accelerate==0.24.1 datasets==2.14.6 peft==0.5.0
      optimum==1.13.2
    - pip install mlrun langchain==0.2.17 openai==1.58.1 langchain_community==0.2.19
      pydub==0.25.1 streamlit==1.28.0 st-annotated-text==4.0.1 spacy==3.7.2 librosa==0.10.1
      presidio-anonymizer==2.2.34 presidio-analyzer==2.2.34 nltk==3.8.1 flair==0.13.0
      htbuilder==0.6.2
    - python -m spacy download en_core_web_lg
    - pip install SQLAlchemy==2.0.31 pymysql requests_toolbelt==0.10.1
    - pip uninstall -y onnxruntime-gpu onnxruntime
    - pip install onnxruntime
    source_code_target_dir: /home/mlrun_code/
    image: .mlrun-project-image-call-center-demo
    base_image: mlrun/mlrun-kfp
  origin_url: git://github.com/mlrun/demo-call-center.git#refs/heads/main
  workflows:
  - image: .mlrun-project-image-call-center-demo
    name: calls-generation
    path: ./src/workflows/calls_generation.py
  - image: .mlrun-project-image-call-center-demo
    name: calls-analysis
    path: ./src/workflows/calls_analysis.py
  params:
    build_image: false
    source: git://github.com/mlrun/demo-call-center.git#main
    gpus: 0
    use_sqlite: false
    default_image: .mlrun-project-image-call-center-demo
  source: git://github.com/mlrun/demo-call-center.git#main
  conda: ''
  default_image: .mlrun-project-image-call-center-demo
