status:
  state: online
spec:
  workflows:
  - path: ./src/workflows/calls_generation.py
    name: calls-generation
  - path: ./src/workflows/calls_analysis.py
    name: calls-analysis
  source: git://github.com/mlrun/demo-call-center.git#main
  owner: shapira
  origin_url: git://github.com/GiladShapira94/demo-call-center.git#refs/heads/cpu-support
  conda: ''
  load_source_on_run: true
  params:
    source: git://github.com/mlrun/demo-call-center.git#main
    default_image: yonishelach/call-center-transformers
    gpus: 0
  default_image: yonishelach/call-center-transformers
  functions:
  - url: hub://structured_data_generator
    name: structured-data-generator
    kind: job
  - url: ./src/calls_generation/conversations_generator.py
    name: conversations-generator
    kind: job
    with_repo: true
  - url: hub://text_to_audio_generator
    name: text-to-audio-generator
    kind: job
  - url: ./src/calls_analysis/db_management.py
    name: db-management
    kind: job
    with_repo: true
  - url: hub://silero_vad
    name: silero-vad
    kind: job
  - url: hub://transcribe
    name: transcription
    kind: job
  - url: hub://pii_recognizer
    name: pii-recognition
    kind: job
    image: guyliguazio/call-center-11.8:1.4.1.6
  - url: hub://question_answering
    name: question-answering
    kind: job
  - url: ./src/calls_analysis/postprocessing.py
    name: postprocessing
    kind: job
  desired_state: online
metadata:
  created: '2024-10-23T07:40:58.160000'
  name: call-center-demo-new5-shapira
kind: project
